# Development environment configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST:localhost}:${DEV_DB_PORT:3307}/${DEV_DB_NAME:motomoto}
    username: ${DEV_DB_USERNAME:myuser}
    password: ${DEV_DB_PASSWORD:mypassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Development Logging
logging:
  level:
    com.motomoto: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG