# Production environment configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # CORS Configuration - Production
  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:https://motomoto.pl}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# Server Configuration
server:
  port: ${PORT:8080}

# Production Logging
logging:
  level:
    com.carportal: INFO
    org.springframework.security: WARN
    org.flywaydb: INFO
    org.springframework.web: WARN
    org.hibernate: WARN